services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./backend/project
      dockerfile: Dockerfile.dev

    ports:
      - '3001:3001'
    volumes:
      - ./backend/project:/app
      - /app/node_modules
    command: npm run dev

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - frontend
  #     - backend
